# Generated by Django 4.2 on 2024-05-17 20:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('catalouge', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producttype',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producttype',
            name='updated_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='productattribute',
            name='attribute_type',
            field=models.PositiveSmallIntegerField(choices=[(2, 'STRING'), (3, 'FLOAT'), (1, 'INTEGER')], default=1),
        ),
    ]
