# Generated by Django 4.2 on 2024-06-08 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalouge', '0003_alter_productattribute_attribute_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productattribute',
            name='attribute_type',
            field=models.PositiveSmallIntegerField(choices=[(3, 'FLOAT'), (1, 'INTEGER'), (2, 'STRING')], default=1),
        ),
    ]
