# Generated by Django 4.2 on 2024-06-09 12:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalouge', '0006_alter_category_parent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalouge.brand'),
        ),
        migrations.AlterField(
            model_name='productattribute',
            name='attribute_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'INTEGER'), (2, 'STRING'), (3, 'FLOAT')], default=1),
        ),
    ]
